
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 09 12:14:48 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int P_CLOSE = 12;
  public static final int LLAVES_APER = 13;
  public static final int P_OPEN = 11;
  public static final int INT = 21;
  public static final int IGUAL = 15;
  public static final int TD_STRING = 3;
  public static final int O_SUMA = 18;
  public static final int MENORQ = 17;
  public static final int TD_INT = 2;
  public static final int PR_IF = 6;
  public static final int O_RESTA = 19;
  public static final int COMA = 10;
  public static final int MAYORQ = 16;
  public static final int FLOAT = 22;
  public static final int TD_CHAR = 4;
  public static final int EOF = 0;
  public static final int CADENA_CARACT = 20;
  public static final int PR_DO = 5;
  public static final int PR_RETURN = 8;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 23;
  public static final int LLAVES_CIERR = 14;
  public static final int PUNTOYC = 9;
  public static final int PR_WHILE = 7;
}

